# Generated by Django 5.0.3 on 2024-03-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='createdate',
            new_name='created_at',
        ),
    ]
